# Generated by Django 4.2.2 on 2023-08-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0012_delete_gradogrupo'),
        ('maestros', '0001_initial'),
        ('alumnos', '0003_alumnotutores_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(default='Sin comentarios.', null=True)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.grado')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='GradoGrupoMaestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grado_grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grados_escolares.gradogrupo')),
                ('id_maestro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='GradoGrupoAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumnos.alumno')),
                ('id_grado_grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grados_escolares.gradogrupo')),
            ],
        ),
    ]
