# Generated by Django 4.2.2 on 2023-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_grado_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='comentarios',
            field=models.CharField(null=True),
        ),
    ]
