# Generated by Django 4.2.2 on 2023-07-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_grupo_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='comentarios',
            field=models.CharField(null=True),
        ),
    ]
