# Generated by Django 4.2.2 on 2023-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_grado_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.AddField(
            model_name='grado',
            name='grupo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
