# Generated by Django 4.2.2 on 2023-08-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_alter_grado_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
                ('comentarios', models.CharField(default='Sin comentarios.', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grado',
            name='subgrado',
        ),
        migrations.CreateModel(
            name='GradoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(default='Sin comentarios.', null=True)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.grado')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.grupo')),
            ],
        ),
    ]
