# Generated by Django 4.2.2 on 2023-08-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_alter_gradogrupo_id_grado_alter_gradogrupo_id_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradogrupo',
            name='id_grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.grado'),
        ),
        migrations.AlterField(
            model_name='gradogrupo',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.grupo'),
        ),
    ]
