# Generated by Django 4.2.2 on 2023-06-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_tiposangre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField()),
                ('curp', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('domicilio', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.sexo')),
            ],
        ),
    ]
