# Generated by Django 4.2.2 on 2023-06-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_tiposangre'),
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tipo_sangre',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalogos.tiposangre'),
        ),
    ]
