# Generated by Django 4.2.2 on 2023-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0003_alter_tutor_tipo_sangre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='tutores/', verbose_name='foto_perfil'),
        ),
    ]
