# Generated by Django 4.2.2 on 2023-06-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0006_alter_tutor_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='parentesco',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
