# Generated by Django 4.2.2 on 2023-06-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0007_tutor_parentesco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='parentesco',
        ),
    ]
