# Generated by Django 4.2.2 on 2023-07-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        ('catalogos', '0002_tiposangre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('codigo_materia', models.CharField(max_length=20)),
                ('detalles_materia', models.TextField(null=True)),
                ('foto_libro', models.ImageField(blank=True, default='sin_foto_libro.png', null=True, upload_to='materias/', verbose_name='foto_libro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cicloescolar')),
                ('id_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.maestro')),
            ],
        ),
    ]
