# Generated by Django 4.2.2 on 2023-07-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_id_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='id_grado',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='id_maestro',
        ),
    ]
